### ISSUE TITLE
Url shortening fails

### ISSUE THREAD

**Issue by mtaki14** [Fuhrmann/keypirinha-url-shortener#1]
15:09:49.956 ** ERROR: URLShortener.URLShortener: b'{\n "error": {\n  "errors": [\n   {\n    "domain": "usageLimits",\n    "reason": "rateLimitExceeded",\n    "message": "Rate Limit Exceeded"\n   }\n  ],\n  "code": 403,\n  "message": "Rate Limit Exceeded"\n }\n}\n'
15:09:49.957 Python: Traceback (most recent call last):
15:09:49.958 Python:   File "C:\Users\ma_t1\Keypirinha\portable\Profile\InstalledPackages\URLShortener.keypirinha-package\urlshortener.py", line 108, in on_suggest
15:09:49.958 Python:   File "C:\Users\ma_t1\Keypirinha\portable\Profile\InstalledPackages\URLShortener.keypirinha-package\services\google.py", line 10, in shorten
15:09:49.958 Python:   File "C:\Users\ma_t1\Keypirinha\portable\Profile\InstalledPackages\URLShortener.keypirinha-package\services\service.py", line 22, in post_request
15:09:49.958 Python:   File "lib\urllib\request.py", line 223, in urlopen
15:09:49.958 Python:   File "lib\urllib\request.py", line 532, in open
15:09:49.958 Python:   File "lib\urllib\request.py", line 642, in http_response
15:09:49.958 Python:   File "lib\urllib\request.py", line 570, in error
15:09:49.958 Python:   File "lib\urllib\request.py", line 504, in _call_chain
15:09:49.958 Python:   File "lib\urllib\request.py", line 650, in http_error_default
15:09:49.958 Python: urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by Fuhrmann** [comment]
I guess this have to do with google shutting down the url shortener service:

"Starting March 30, 2018, we will be turning down support for goo.gl URL shortener. From April 13, 2018 only existing users will be able to create short links on the goo.gl console."

Because in the google console API there are almost no calls:

![image](https://user-images.githubusercontent.com/1160365/38871570-41d3f48c-421f-11e8-81f6-9f1d7cac3a3b.png)

I'll have to take a look at the suggested alternative: Firebase Dynamic Links, implement in this package and remove google support!

**Comment by mtaki14** [comment]
Not sure if you changed something but it works fine now.

**Comment by Fuhrmann** [comment]
Didn't have time to take a look, but nice. If you have any problems just create a new issue.
